language: rust
rust:
  - nightly
  - beta
  - stable
sudo: 9000
dist: xenial
os:
  - linux
  - osx
osx_image: xcode10.2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-5.0
    packages:
      - autoconf2.13
      - gcc-7
      - g++-7
      - clang-5.0
  homebrew:
    update: true
    packages:
      - python
      - python@2
      - autoconf@2.13
      - ccache
      - llvm
      - yasm

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

before_script:
  - rustup component add rustfmt-preview
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7; export CXX=g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHON3="/usr/local/opt/python/bin/python3"; fi

script:
  - ccache -z
  - CCACHE=$(which ccache) travis_wait 30 cargo build --verbose $FEATURES
  - CCACHE=$(which ccache) RUST_BACKTRACE=1 cargo test --lib --verbose $FEATURES
  - ccache -s

cache: ccache
