language: rust
channel: nightly
sudo: 9000

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
- CC="gcc-4.8" CPP="gcc-4.8 -E" CXX="g++-4.8"

script:
  - travis_wait cargo build --verbose

notifications:
  webhooks: http://build.servo.org:54856/travis
