language: rust
rust:
  - nightly
sudo: 9000
dist: trusty

os:
  - linux
  - osx

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

script:
  - cargo build --verbose --verbose $FEATURES

before_install:
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install yasm; fi

notifications:
  webhooks: http://build.servo.org:54856/travis
