version: 1.0.{build}
image: Visual Studio 2017

matrix:
  fast_finish: true

environment:
  LINKER: "lld-link.exe"
  PYTHON3: "C:\\Python37-x64\\python.exe"
  # The appveyor image we use has a pretty huge set of things installed... we make the
  # initial PATH something sane so we know what to expect
  PATH: "C:\\windows\\system32;\
    C:\\windows;\
    C:\\windows\\System32\\Wbem;\
    C:\\windows\\System32\\WindowsPowerShell\\v1.0;\
    C:\\ProgramData\\chocolatey\\bin;\
    C:\\Python27;\
    C:\\Tools\\PsTools;\
    C:\\Tools\\NuGet3;\
    C:\\Program Files\\Microsoft\\Web Platform Installer\\;\
    C:\\Program Files\\7-Zip;\
    C:\\Program Files\\Mercurial;\
    C:\\Program Files (x86)\\Subversion\\bin;\
    C:\\Program Files (x86)\\CMake\\bin;\
    C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;\
    C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;\
    C:\\Program Files\\Amazon\\AWSCLI\\;\
    C:\\Program Files\\Microsoft Windows Performance Toolkit\\;\
    C:\\Program Files\\LLVM\\bin;\
    C:\\Program Files\\Git LFS;\
    C:\\Program Files\\Git\\cmd;\
    C:\\Program Files\\Git\\usr\\bin;\
    C:\\Program Files\\AppVeyor\\BuildAgent;"

  CC: "clang-cl.exe"
  CXX: "clang-cl.exe"

  matrix:
    - DEBUGMOZJS: ''
    - DEBUGMOZJS: --features debugmozjs

# Uncomment to enable RDP & wait for exit.  Connection info will be printed in the log.
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# called after cloning, before building
install:
  - ps: Start-FileDownload "http://servo-rust.s3.amazonaws.com/build/MozillaBuildSetup-2.2.0.exe"
  - ps: .\MozillaBuildSetup-2.2.0.exe /S | Out-Null
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host=x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set MOZTOOLS_PATH=C:\mozilla-build\msys\bin;C:\mozilla-build\mozmake;C:\mozilla-build\yasm
  - set NATIVE_WIN32_PYTHON=C:/Python27/python.exe
  - set AUTOCONF=C:/mozilla-build/msys/local/bin/autoconf-2.13
  - rustc -vV
  - cargo -vV

build_script:
  - echo PATH %PATH%
  - echo MOZTOOLS_PATH %MOZTOOLS_PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - cargo test --verbose --verbose %DEBUGMOZJS% --lib
