[[engine]]
engine = "WinterJS"
# stress_duration = 10
# max_concurrent_connections = 100
# min_connections = 2000
# max_connections = 20000

# [[engine]]
# engine = "Wrangler"

[[test_case]]
test_name = "1-hello"
test_route = "1-hello"
expected_output = "hello"
expected_response_status = 200

[[test_case]]
test_name = "2-blob"
test_route = "2-blob"
expected_output = "Hello, world!"
expected_response_status = 200

[[test_case]]
test_name = "2.1-file"
test_route = "2.1-file"
expected_output = "All tests passed!"
expected_response_status = 200

[[test_case]]
test_name = "3.1-headers"
test_route = "3-headers"
expected_output = "All Headers:\ncontent-type: text/plain\nx-custom-header: CustomValue\n"
expected_response_status = 200

[[test_case]]
test_name = "3.2-headers"
test_route = "3-headers/append"
expected_output = "Header appended"
expected_response_status = 200

[[test_case]]
test_name = "3.3-headers"
test_route = "3-headers/delete"
expected_output = "Header deleted"
expected_response_status = 200

[[test_case]]
test_name = "3.4-headers"
test_route = "3-headers/get"
expected_output = "Content-Type is text/plain"
expected_response_status = 200

[[test_case]]
test_name = "3.5-headers"
test_route = "3-headers/set"
expected_output = "Content-Type set to text/html"
expected_response_status = 200

[[test_case]]
test_name = "3.6-headers"
test_route = "3-headers/has"
expected_output = "Has Content-Type: true"
expected_response_status = 200

[[test_case]]
test_name = "3.7-headers"
test_route = "3-headers/iterate"
expected_output = "Headers iterated:\ncontent-type: text/plain\nx-custom-header: CustomValue\n"
expected_response_status = 200

[[test_case]]
test_name = "4-request"
test_route = "4-request"
expected_output = "{\"method\":\"POST\",\"headers\":{\"x-test-header\":\"TestValue\"},\"referrer\":\"about:client\",\"referrerPolicy\":\"about:client\",\"mode\":\"cors\",\"credentials\":\"omit\",\"cache\":\"default\",\"redirect\":\"follow\",\"integrity\":\"\",\"keepalive\":false,\"isReloadNavigation\":false,\"isHistoryNavigation\":false,\"signal\":{},\"duplex\":\"half\"}"
expected_response_status = 200

[[test_case]]
test_name = "5-response"
test_route = "5-response"
expected_output = "All tests passed"
expected_response_status = 200

[[test_case]]
test_name = "6-text-encoder"
test_route = "6-text-encoder"
expected_output = "All tests passed!"
expected_response_status = 200

[[test_case]]
test_name = "7-text-decoder"
test_route = "7-text-decoder"
expected_output = "All tests passed!"
expected_response_status = 200

[[test_case]]
test_name = "8-url"
test_route = "8-url"
expected_output = "All tests passed!"
expected_response_status = 200

[[test_case]]
test_name = "8.1-search-params"
test_route = "8.1-search-params"
expected_output = "All tests passed!"
expected_response_status = 200

[[test_case]]
test_name = "10-atob-btoa"
test_route = "10-atob-btoa"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "11-fetch"
test_route = "11-fetch"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "11.1-fetch-body"
test_route = "11.1-fetch-body"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "12-streams"
test_route = "12-streams"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "12.1-transform-stream"
test_route = "12.1-transform-stream"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "12.2-text-encoder-stream"
test_route = "12.2-text-encoder-stream"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "12.3-text-decoder-stream"
test_route = "12.3-text-decoder-stream"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "13-performance"
test_route = "13-performance"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "14-form-data"
test_route = "14-form-data"
expected_output = "All Tests Passed!"
expected_response_status = 200

[[test_case]]
test_name = "15-timers"
test_route = "15-timers"
expected_output = "All Tests Passed!"
expected_response_status = 200